#基本運算

In [2]:
a = [1, 3, 5, 7]
b = [2, 4, 6, 8]
print(a)
print(a[0])
print(type(a))
print(type(a[0]))
c = a + b
print(c)
d = [x+y for x, y in zip(a,b)]
print(d)

[1, 3, 5, 7]
1
<class 'list'>
<class 'int'>
[1, 3, 5, 7, 2, 4, 6, 8]
[3, 7, 11, 15]


In [7]:
import numpy as np
x1 = np.array([1, 3, 5, 7])
x2 = np.array(b)
print(x2)
print(type(x2))
x3 = x1 ** x2
print(x3)

[2 4 6 8]
<class 'numpy.ndarray'>
[      1      81   15625 5764801]


np.array 陣列的產生
int8, int16, int32, int64 整數bits數
float16, float32, float64
uint8, uint16, uint32, uint64 正整數
np.linspace(start, stop, num=50)

In [20]:
a = np.array((0,1,2,3,4,5,6,7,8,9))
b = np.arange(0,10,3) #np.arange(start=0,stop,step=1)
print(b)
c = np.arange(0.1, 10, 1.1)
d = np.array([1, 2.1, 3, 4, 5])
print(d)
e = np.array([1, 2.1, 3, 4, 5],dtype=np.int8)
print(e)
print(e.shape)
f = np.linspace(0,10,11)
print(f)
g = np.linspace(0,10)
print(g)
h = np.arange(10)
print(h)

[0 3 6 9]
[1.  2.1 3.  4.  5. ]
[1 2 3 4 5]
(5,)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[0 1 2 3 4 5 6 7 8 9]


2D ndarray #維度, 陣列的大小, 第0軸的維度大小是2, 第1軸的維度大小是3@


In [28]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)
print(a.shape)

b = np.arange(0,12).reshape((3,4)) #重塑,把原始的陣列轉換成3x4的2D陣列
print(b)
b = np.arange(0,15).reshape((-1,5)) #某一個維度值可以給-1,讓系統自動算
c = np.random.randint(1,10,size=(3,4)) #randint(start,stop,size=(a,b))
print(c)                               #產生axb的2D陣列，裡面的值是介於start和stop之間的整數
d = np.random.rand(2,3) #產生2x3的2D陣列,裡面的值是介於0到1的亂數
print(d)
e = np.random.randn(2,3) #產生2x3的2D陣列,裡面的值是服從標準常態分佈的亂數
print(e)
f = np.zeros((2,3)) #產生全部為0的2x3的2D陣列
print(f)
g = np.zeros_like(c) #產生和陣列c一樣大小的2D陣列
print(g)
h = np.ones((2,3)) #產生全部為1的2x3的2D陣列
print(h)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 9 3 6]
 [1 9 3 2]
 [8 1 6 8]]
[[0.33179163 0.26700757 0.38812797]
 [0.65095789 0.95600885 0.87834769]]
[[-1.01491977 -0.63492337  0.40185923]
 [ 0.05243358 -0.92271069 -0.58029023]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


基本運算/軸的觀念
np.sum(array,axis=?) #依axis=?的值,對陣列作加總

In [52]:
#np.random.seed(10)
a = np.random.randint(10,size=(3,4))
print(a)
sumA = np.sum(a) #沒有給axis的參數,則對陣列a的所有元素作加總
print(sumA)
sumA2 = a.sum() #直接用實體物作a呼叫sum函數作加總運算
print(sumA2)
sumAxis0 = np.sum(a, axis=0) #依第0軸的方向作加總
print(sumAxis0)

[[6 5 6 0]
 [0 6 9 1]
 [8 9 1 2]]
53
53
[14 20 16  3]
