In [ ]:
a=[1,3,5]
b=[2,4,6]

In [ ]:
import numpy as np
x1=np.array ([1,3,5])
print(x1)

[1 3 5]


In [ ]:
a = np.array((0,1,2,3,4,5))
b = np.arange(0,10,1)
print(b)
c = np.arange(0.1,10,1.1)
d = np.array([1,2.1,3,4,5])
print(d)
e = np.array([1,2.1,3,4,5],dtype=np.int8)
print(type(e))
print(e)
print(e.shape)
f = np.linspace(0,10,11)
print(f)


[0 1 2 3 4 5 6 7 8 9]
[1.  2.1 3.  4.  5. ]
<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


2D 

In [ ]:
a = np.array([[0,1,2,3,4],[3,4,5,6,5],[13,14,15,16,15]])
print(a)
print(a.shape)

b= np.arange(0,15).reshape((3,-1))
print(b)
c = np.random.randint(1,10,size=(3,4))
print(c)
d = np.random.rand(2,3)
print(d)
e = np.random.randn(2,3)
print(e)
f = np.zeros((2,3))
print(f)
g = np.zeros_like(c)
print(g)
h = np.ones((2,3))
print(h)

[[ 0  1  2  3  4]
 [ 3  4  5  6  5]
 [13 14 15 16 15]]
(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[3 5 7 5]
 [8 9 9 5]
 [1 2 4 3]]
[[0.10988344 0.84098185 0.82227558]
 [0.30193954 0.61419388 0.30995903]]
[[-0.72515964  1.50825412 -0.31446119]
 [-1.61643088  0.33756277  1.10609174]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.arange(1,10).reshape((3,-1))
print(a)
sumA = np.sum(a)
print(sumA)
sumAxis0 = np.sum(a, axis=1)
print(sumAxis0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]
