In [2]:
import numpy as np
a = np.arange(12)
b1 = np.reshape(a, (3,4))
b2 = np.reshape(a, (3,4))
print(a)
print(b1)
print(b2)
b1[0,0] = -1
print(b1)
print(a)
b2[0,1] = -2
print(b2)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-1  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[-1  1  2  3  4  5  6  7  8  9 10 11]
[[-1 -2  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[-1 -2  2  3  4  5  6  7  8  9 10 11]


In [7]:
print(a)
b3 = np.resize(a, (2, 3))
b4 = np.resize(a, (4, 5))
print(b3)
print(b4)

[-1 -2  2  3  4  5  6  7  8  9 10 11]
[[-1 -2  2]
 [ 3  4  5]]
[[-1 -2  2  3  4]
 [ 5  6  7  8  9]
 [10 11 -1 -2  2]
 [ 3  4  5  6  7]]


合併

In [11]:
a = np.arange(3)
print(a)
b = np.append(a,[2, 4])#a合併[2, 4]
print(b)
c = np.append(a,a)
print(c)

[0 1 2]
[0 1 2 2 4]
[0 1 2 0 1 2]


In [27]:
a2 = np.arange(6).reshape(2, 3)
b2 = np.zeros_like(a2)#zeros_like生成全部0
c2 = np.ones((3, 3))#ones生成全部1
d2 = np.append(a2, b2, axis=1)
print(a2)
print(b2)
print(d2)
print(c2)
e2 = np.append(a2, c2, axis=0)
print(e2)

[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]
[[0 1 2 0 0 0]
 [3 4 5 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
print(a2)
print(b2)
f2 = np.hstack((a2,b2))#hstack=append的axis=1
print(f2)
g2 = np.vstack((a2,b2))#vstack=append的axis=0
print(g2)

[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]
[[0 1 2 0 0 0]
 [3 4 5 0 0 0]]
[[0 1 2]
 [3 4 5]
 [0 0 0]
 [0 0 0]]


轉置

In [9]:
a2 = np.arange(6).reshape(2,3)
print(a2)
a2t = a2.T
print(a2t)
a2t2 = np.transpose(a2)
print(a2t2)
print("==========")
a3 = np.random.randint(10, size=(2,3,4))
print(a3)
print(a3.shape)
print("==========")
a3t = np.transpose(a3, axes=(1,0,2))
print(a3t)
print(a3t.shape)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[[6 7 7 5]
  [3 0 6 9]
  [1 6 4 1]]

 [[1 3 7 3]
  [9 6 2 3]
  [9 2 7 9]]]
(2, 3, 4)
[[[6 7 7 5]
  [1 3 7 3]]

 [[3 0 6 9]
  [9 6 2 3]]

 [[1 6 4 1]
  [9 2 7 9]]]
(3, 2, 4)


排序sort,argsort

In [25]:
a = np.random.randint(10,size=6)
#a = np.random.randint(10, size=(2,3))
print(a)
print("========")
sa = np.sort(a)#排序 
print(sa)
print("========")
saindex = np.argsort(a)#排序值的位子
print(saindex)
print("========") 
print(a[saindex])
print(sa[-3:])

[5 4 9 2 9 3]
[2 3 4 5 9 9]
[3 5 1 0 2 4]
[2 3 4 5 9 9]
[5 9 9]


In [29]:
a2 = np.random.randint(10, size=(2,3))
sa2 = np.sort(a2, axis=0)#排序欄
sa2index = np.argsort(a2, axis=0)
print(a2)
print(sa2)
print(sa2index)

[[8 7 3]
 [5 4 4]]
[[5 4 3]
 [8 7 4]]
[[1 1 0]
 [0 0 1]]


In [32]:
vaules = [(2113001,'aaa',90,70,80),(2113002,'bbb',45,88,74),(2113003,'ccc',10,80,30),(2113004,'ddd',90,77,33)]
dt = [('id',int),('name','U10'),('chScore',int),('enScore',int),('mathScore',int)]
data = np.array(vaules,dtype=dt)
print(data)
sortData = np.sort(data, order=['chScore'])#用chScore排序
print(sortData)
sortData2 = np.sort(data, order=['chScore','enScore'])
print(sortData2)



[(2113001, 'aaa', 90, 70, 80) (2113002, 'bbb', 45, 88, 74)
 (2113003, 'ccc', 10, 80, 30) (2113004, 'ddd', 90, 77, 33)]
[(2113003, 'ccc', 10, 80, 30) (2113002, 'bbb', 45, 88, 74)
 (2113001, 'aaa', 90, 70, 80) (2113004, 'ddd', 90, 77, 33)]
[(2113003, 'ccc', 10, 80, 30) (2113002, 'bbb', 45, 88, 74)
 (2113001, 'aaa', 90, 70, 80) (2113004, 'ddd', 90, 77, 33)]


單位矩陣

In [44]:
a = np.identity(5)#5*5的單位矩陣
print(a)
b = np.eye(5)#5*5的單位矩陣
print(b)
c = np.eye(5,7)#5*7的單位矩陣
print(c)
d = np.eye(5,k=1)#1的位子開始
print(d)
e = np.eye(5,k=-1)#-1欄的位子開始
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


壓平,np.flatten(), npravel()

In [49]:
a2 = np.arange(6).reshape(2,3)
print(a2)
b = a2.flatten()#生成新的a2
print(b)
b[1] = 9
print(b)
print(a2)

c = np.ravel(a2)#原本的a2
print(c)
c[1]=9
print(a2)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 9 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 9 2]
 [3 4 5]]
