陣列合併np.r_[x,y,z]x是指在哪一個軸合併, y是指變幾軸,z是指把要合併的資料變幾軸
,np.c_[]

In [48]:
import numpy as np 
import pandas as pd
a = np.r_[0:10:1]
print(a)
a = np.r_[:10]
print(a)
b = np.r_[5:,a]#合併[0到4]和a
print(b)
c = np.r_[1, 11, a, b, np.array([2,3]),np.random.rand(3)]
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 1 2 3 4 5 6 7 8 9]
[ 1.         11.          0.          1.          2.          3.
  4.          5.          6.          7.          8.          9.
  0.          1.          2.          3.          4.          0.
  1.          2.          3.          4.          5.          6.
  7.          8.          9.          2.          3.          0.26101563
  0.29313923  0.73603892]


In [38]:
a =np.arange(3)
print(a)
b = np.zeros_like(a)
print(b)
c = np.r_['0', a, b ]
print(c)
d = np.r_['0,2,0', a, b]#['0,2,0']是指第0欄(直的) 2是指2城 0是指把原是資料變直的
print(d)
e = np.r_['0,2, 1', a, b]#['0,2,1']是指第0欄(直的) 2是指2城 0是指把原是資料變橫的
print(e)
f = np.r_['1,2,0',a,b]
print(f)


[0 1 2]
[0 0 0]
[0 1 2 0 0 0]
[[0]
 [1]
 [2]
 [0]
 [0]
 [0]]
[[0 1 2]
 [0 0 0]]
[[0 0]
 [1 0]
 [2 0]]


In [52]:
a = np.zeros((2,3))
print(a)
b =np.ones_like(a)
print(b)
c = np.r_[a,b]
print("c",c)
d = np.r_['1',a,b]
print("d",d)
e = np.r_['0,3,0',a,b]
print("e",e)
f = np.r_['1,3,0',a,b]
print(f)




[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
c [[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
d [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
e [[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
[[[0.]
  [0.]
  [0.]
  [1.]
  [1.]
  [1.]]

 [[0.]
  [0.]
  [0.]
  [1.]
  [1.]
  [1.]]]


In [89]:
a = np.zeros((2,3))
b =np.ones_like(a)
c = np.r_['3,5,3',a,b]
print(c)
d = np.r_['4,5,1',a,b]
e = np.r_['-1',a,b]
f = np.c_[a,b]



[[[[[0. 0. 0.]
    [0. 0. 0.]
    [1. 1. 1.]
    [1. 1. 1.]]]]]


抽選,choice

In [58]:
name = np.array(['pe','al','jo','po'])
x = np.random.choice(name, 3)
print(x)
x = np.random.choice(name,3,replace=False)#抽3次 replace=False是不重複
print(x)
prob = [0.05,0.1,0.1,0.75]
x = np.random.choice(name,10,p=prob)#p是指機率
print(x)



['jo' 'al' 'jo']
['al' 'jo' 'po']
['po' 'po' 'al' 'po' 'pe' 'po' 'po' 'po' 'po' 'po']


In [60]:
a = np.arange(10)
print(a)
np.random.shuffle(a)#隨機排列
print(a)

[0 1 2 3 4 5 6 7 8 9]
[7 4 1 0 5 2 9 8 6 3]


In [61]:
a = np.random.rand(5,6)
print(a)
np.save('data_a',a)
b = np.load('data_a.npy')
print(b)


[[0.47841468 0.55740913 0.40588999 0.14443531 0.94856161 0.98968699]
 [0.11246549 0.50469203 0.4266077  0.46514871 0.84786804 0.69543892]
 [0.77931843 0.23698606 0.34233008 0.31294239 0.3858799  0.01926344]
 [0.86370232 0.99337835 0.38256035 0.98649968 0.53661066 0.42731165]
 [0.62246416 0.51052591 0.50538296 0.80414463 0.46832281 0.29499871]]
[[0.47841468 0.55740913 0.40588999 0.14443531 0.94856161 0.98968699]
 [0.11246549 0.50469203 0.4266077  0.46514871 0.84786804 0.69543892]
 [0.77931843 0.23698606 0.34233008 0.31294239 0.3858799  0.01926344]
 [0.86370232 0.99337835 0.38256035 0.98649968 0.53661066 0.42731165]
 [0.62246416 0.51052591 0.50538296 0.80414463 0.46832281 0.29499871]]


In [63]:
np.savetxt('datatxt.txt',a,fmt='%.2f')#變取小數2位
c = np.loadtxt('datatxt.txt')
print(c)
c = np.loadtxt('datatxt.txt',usecols=(0,5))#取前2的
print(c)
c = np.loadtxt('datatxt.txt',skiprows=3,usecols=(0,5))#skiprows跳過幾行
print(c)



[[0.48 0.56 0.41 0.14 0.95 0.99]
 [0.11 0.5  0.43 0.47 0.85 0.7 ]
 [0.78 0.24 0.34 0.31 0.39 0.02]
 [0.86 0.99 0.38 0.99 0.54 0.43]
 [0.62 0.51 0.51 0.8  0.47 0.29]]
[[0.48 0.99]
 [0.11 0.7 ]
 [0.78 0.02]
 [0.86 0.43]
 [0.62 0.29]]
[[0.86 0.43]
 [0.62 0.29]]
