10/21  基本函數
欄是直的 

In [115]:
import numpy as np
import pandas as pd
a = np.random.randint(12, size=(3,4))
print(a)
sar = np.max(a)#<=====A的最大值
print(sar)
sar0 = np.max(a, axis= 0)#<=====A每一欄最大值
print(sar0)
sarindex = np.argmax(a, axis=0)#<=====A每一欄的最大值在哪一列的位子
print(sarindex)

[[10  8  0  2]
 [ 9  9 11  5]
 [ 1  4  4 11]]
11
[10  9 11 11]
[0 1 1 2]


In [116]:
b  = np.random.randint(6, size=(2,3,4))#<====(隨機生成0~5的值)(2個表格(2軸))(3*4的表格)(3欄4列))
print(b)
maxB = np.max(b, axis=-1)# -1重最後開始
print(maxB)

[[[3 0 2 4]
  [4 3 0 2]
  [0 3 3 5]]

 [[3 5 2 1]
  [5 3 4 3]
  [1 1 4 4]]]
[[4 4 5]
 [5 5 4]]


In [117]:
b = np.random.rand(10,4)#<====隨機生成0~1的小數(3欄4列))
lables = np.array(['hu','do','ca','bi'])#b每一欄的最大值在哪一列的位子(列變成檢視的文字)
print(b)
outindex = np.argmax(b, axis=1)
print(lables[outindex])
c = pd.DataFrame(b) #<========把b變成pd額的表格
print(c)

[[0.84595762 0.57371106 0.44093134 0.68168632]
 [0.2853669  0.57527627 0.2913936  0.13258719]
 [0.76863621 0.76311969 0.72175504 0.41349791]
 [0.86504711 0.69526175 0.65299477 0.52855419]
 [0.43022496 0.60901843 0.26522491 0.90879742]
 [0.70306701 0.77611842 0.2232087  0.30321841]
 [0.62372915 0.15586001 0.71565392 0.68757914]
 [0.30284111 0.29951943 0.77616139 0.32448423]
 [0.59665683 0.7063245  0.89820998 0.9196979 ]
 [0.59749128 0.92464846 0.12670497 0.54502052]]
['hu' 'do' 'hu' 'hu' 'bi' 'do' 'ca' 'ca' 'bi' 'do']
          0         1         2         3
0  0.845958  0.573711  0.440931  0.681686
1  0.285367  0.575276  0.291394  0.132587
2  0.768636  0.763120  0.721755  0.413498
3  0.865047  0.695262  0.652995  0.528554
4  0.430225  0.609018  0.265225  0.908797
5  0.703067  0.776118  0.223209  0.303218
6  0.623729  0.155860  0.715654  0.687579
7  0.302841  0.299519  0.776161  0.324484
8  0.596657  0.706324  0.898210  0.919698
9  0.597491  0.924648  0.126705  0.545021


np.all(array)--->True,False
np.any(array)---->True,False
np.where(array,[x],[y])--->不為0的位子

In [118]:
a = np.random.randint(2, size=6)
print(a)
print(np.all(a))#
print(np.any(a))
print(np.where(a))

[1 1 1 0 1 1]
False
True
(array([0, 1, 2, 4, 5], dtype=int64),)


In [119]:
a = np.random.randint(11, size=(3,3))
c = pd.DataFrame(a) #<========把a變成pd額的表格
print(c)
print(np.where(a>5))#<======取大於5的數


    0  1   2
0  10  1  10
1   4  1   2
2   3  8   6
(array([0, 0, 2, 2], dtype=int64), array([0, 2, 1, 2], dtype=int64))


In [120]:
import pandas as pd
a = np.random.randint(11, size=(3,3))#<====隨機生成0~10的數(3欄3列))
c = pd.DataFrame(a) #<========把a變成pd額的表格
print(c)
print(np.where(a>5,"big","small"))#<======取大於5的數變big 小於5變small

   0   1  2
0  8   7  1
1  3   4  4
2  4  10  7
[['big' 'big' 'small']
 ['small' 'small' 'small']
 ['small' 'big' 'big']]


In [121]:
a = np.random.randint(-5,5, size=(2,3))
print(pd.DataFrame(a))
print(np.where(a<0,),a**2,a)#<=====把小於0的值平方

   0  1  2
0 -3 -3 -2
1 -1 -3 -4
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64)) [[ 9  9  4]
 [ 1  9 16]] [[-3 -3 -2]
 [-1 -3 -4]]


擴張,展開

In [122]:
a = np.arange(3)#<======生成0到2的值
print(a)
b = a + 1#<=======把a全+1
#print(b)


[0 1 2]


In [123]:
a2 = np.arange(6).reshape(2,3)
print(a2)
print(a+a2)#<=====(a+a2)>([0 1 2]+[0 1 2])([0 1 2]+[3 4 5])

[[0 1 2]
 [3 4 5]]
[[0 2 4]
 [3 5 7]]


In [124]:
a = np.array([0,1,2,])
b = a[np.newaxis,:]#newaxis是生成一個欄   a是[[1,2,3][]]
c = a[:,np.newaxis]#a是[1,2,3]  [[1][2][3]]
print(b.shape)
print(c.shape)
distA = np.empty((3,3))
for i ,ar in enumerate(a):#enumerate是下標的值
    for j ,ac in enumerate(a):
        distA[i,j] = int(((ar-ac)**2)**0.5)
print(distA)


(1, 3)
(3, 1)
[[0. 1. 2.]
 [1. 0. 1.]
 [2. 1. 0.]]


In [125]:
a = np.arange(4)
b = a[np.newaxis,:]
c = a[:,np.newaxis]
d=((b-c)**2)**0.5
print(pd.DataFrame(d))


     0    1    2    3
0  0.0  1.0  2.0  3.0
1  1.0  0.0  1.0  2.0
2  2.0  1.0  0.0  1.0
3  3.0  2.0  1.0  0.0


2D

In [126]:
a = np.arange(6).reshape(3,2)
print(a)
print(pd.DataFrame(a))
for i ,ar in enumerate(a):#enumerate是下標的值
    for j ,ac in enumerate(a):
        distA[i,j] =(((ar[0]-ac[0])**2+(ar[1]-ac[1])**2)**0.5)
print(a)
print(distA)

[[0 1]
 [2 3]
 [4 5]]
   0  1
0  0  1
1  2  3
2  4  5
[[0 1]
 [2 3]
 [4 5]]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [127]:
a = np.arange(6).reshape(3,2)
b = a[np.newaxis,:,:]
c = a[:,np.newaxis,:]
d=np.sum((c-b)**2,axis=-1)**0.5
print(d)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]
